### ISSUE TITLE
deploying to DigitalOcean, Ubuntu 16.04

### ISSUE THREAD

**Issue by ghukill** [WSULib/AgBox#4]
Had to manually install python 2.7 on the target server, as `ansible ping` was revealing that `/usr/bin/python` could not be found on remote server.

Not the end of the world, but looks like some people bake this into their ansible build?
```
- hosts: all
  gather_facts: no
  tasks:
    - name: Bootstrap Python runtime
    - raw: /usr/bin/apt-get update && /usr/bin/apt-get install -y python2.7 python-apt
```

Even then, I had to create a symlink from `/usr/bin/python2.7` to `/usr/bin/python`, and I'm not sure the above would cover that too...

Just noting here.
